FROM node:12.16.1

RUN mkdir -p /app
WORKDIR /app
# Installs git
# RUN yum install -y git

# définit le dossier 'app' comme dossier de travail
#WORKDIR /app
#RUN ls -lah

# copie 'package.json' et 'package-lock.json' (si disponible)
#COPY package*.json ./

# installe les dépendances du projet
#RUN npm install
#RUN ls -lah
#CMD npm run serve
#CMD npm run serve --prefix client
